version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  get-routes:
    build:
      context: ./bGames-API-GET
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_DATABASE: mydatabase
    depends_on: 
      - db

  post-routes:
    build:
      context: ./bGames-API-POST
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_DATABASE: mydatabase
    depends_on: 
      - db

  user-routes:
    build:
      context: ./bGames-User-Management
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_DATABASE: mydatabase
    depends_on: 
      - db

volumes:
  db-data:
